language: cpp
env:
- QT_BASE=4
- QT_BASE=5
install:
- sudo apt-get update -qq
- sudo apt-get install -qq qt${QT_BASE}-default qt${QT_BASE}-qmake
script:
- qmake
- make
after_success:
- tar -zcvf bin/bin-VeloDT-prerelease-ubuntu-qt${QT_BASE}-x86_64.tar.gz bin/V2RhoT bin/V2T
before deploy:
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
- git tag dev -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
- git push -q https://$TAGPERM@github.com/cmeessen/VeloDT/tree/restructure-repo --tags
deploy:
  provider: releases
  skip_cleanup: true
  prerelease: true
  overwrite: true
  file: bin/bin-VeloDT-prerelease-ubuntu-qt${QT_BASE}-x86_64.tar.gz
  api_key:
    secure: Ai5KZ93A+auIU7Rrq/8DqKQL8Qk3k0nCf88ybi0ssRXiwlkVSS79j0xUrGm4ih8+YlF1GYMKGvZuVjBg0UGBf4m2ed0akEFQe+8v1JG3caq1xlpJiDntUpTEu5gb0WNtj0FrRTsIat5s2oNfUikiVNS7o1QUDpGzce/PzFceSZ2qeiMdYwlWpGod2gE8iwyn58M95UvkVwNhxQwnOGpk3+6rB34nsM099WimMgm7LVi2FnOhPD4mDnQrOzt1d6rPrF4zzQqPZonmrQcWLGqH5+YDYttBSMSKnkWIUSodHSyxuZJUD/QtgWmlynyXG0Zfa8OfVbXA1D+DaFWQuHHd2rO2tLnCYgWTzd2hfSf1/LOp6FxJCerdKkY3Y8K2s0OMOewGeuhOrrEsLGYRJJavsxQKgD9O+C2M5mzdd+UusQ4KJHjJ+y/6hncJvrh96aHq9Im6wNlnGppAsd1mPlV1deq4dLoy6+zWx4/idqlUZuELAbW9zeEMRC/hD5qNs7s9wxgGoyknYCGUI1tXrxtoh0aPfqNvbzX0aTDRBZ9SE1yCbIfs1HXGRqmXxTN2ktVb1+z1TufkLQe+fXZjzr9R5/BSSMZM5ZF2JGLcqZIdn/0ZE/F3LFfVWiCgfFPPotSVD4e3xpQV06RcNIG/RLGNkV0W6Xxx2ubOLZJZ0hPIns8=
  on:
    repo: cmeessen/VeloDT
    branch: restructure-repo
